name: flutter_kokkai_gijiroku
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0-5.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^1.0.0
  json_annotation: ^4.4.0

  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.0.0-dev.0

  http: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner: ^2.0.0
  freezed: ^1.0.0
  json_serializable: ^6.0.0

flutter:
  uses-material-design: true
