name: flutter_kokkai_gijiroku
description: 国会会議録検索システム 検索用API 非公式クライアントアプリケーション
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0
  url_launcher: ^6.0.0
  xml: ^6.0.0

  http: ^0.13.0
  go_router: ^6.0.0

  freezed_annotation: ^2.0.0
  json_annotation: ^4.8.0
  riverpod_annotation: ^2.0.0

  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.0.0

  hive: ^2.0.0
  hive_flutter: ^1.0.0

  http_hive_cache: ^0.0.1

  google_fonts: ^4.0.0
  quiver: ^3.0.0
  breakpoints_mq: ^2.0.0
  paging_view: ^1.0.0
  flutter_linkify: ^5.0.0
  sticky_headers: ^0.3.0
  over_bottom_sheet: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner: ^2.0.0
  freezed: ^2.0.0
  json_serializable: ^6.0.0
  riverpod_generator: ^2.0.0
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
